apiVersion: v2
appVersion: v2.0.2

name: influxdb2
description: A Helm chart for InfluxDB v2
home: https://www.influxdata.com/products/influxdb-overview/influxdb-2-0/
type: application
version: 1.0.12
maintainers:
  - name: rawkode
    email: rawkode@influxdata.com
  - name: gitirabassi
    email: giacomo@influxdata.com
